### ISSUE TITLE
Spark_Prop06: an experiment with individual packages.

### ISSUE THREAD

**Issue by Blady-Com** [jcdubois/moth#5]
Hello,
I have split os.ads / os.adb in several individual packages in order to separate the functionalities and to make easier my comprehension ;-)
Not sure it helped proofs.
Not sure it does still work.
Maybe some adjustments on the content of the packages are necessary.

Nevertheless, the medium failed checks have been reduced to six remaining.
I've add for each a comment in the source code with a question: -- Q:...

I haven't yet submit a pull request (no regression verification done yet), just pushed the branch on my repo:
https://github.com/Blady-Com/moth/tree/spark_prop06/kernel/core
What is your feedback?
HTH, Pascal.

**Comment by jcdubois** [comment]
Thanks Pascal,
Your proposal has inspire me and I have split the source code in multiple packages on the spark_modulaire branch.
The proof is still to be improved/worked out.
